### ISSUE TITLE
Making the code shorter...

### ISSUE THREAD

**Issue by WestfW** [MarcelMG/AVR8_BitBang_UART_TX#1]
Nicely explained, but your code contains a common "mistake" that causes it to be larger than it needs to be....
`volatile uint16_t tx_shift_reg = 0;`
Yes, tx_shift_reg needs to be volatile so that it is read/written "agressively" in both the mainline and ISR code.  However, a code sequence like the following:
```
   if(tx_shift_reg){return;}
   //fill the TX shift register witch the character to be sent and the start & stop bits
   tx_shift_reg = (character<<1);
   tx_shift_reg &= ~(1<<0); //start bit
   tx_shift_reg |= (1<<9); //stop bit
```
Will cause the RAM to be accessed EACH TIME - 3 reads and 3 writes, of 16 bits, when there is no chance that the contents actually change over that time.  If you explicitly move the value into a local variable (ie register, where it needs to be to be operated on, anyway), you can cut down the size quite a bit.  Similar for the ISR:
~~~
void UART_tx(char character)
{
   uint16_t td = tx_shift_reg;
   //if sending the previous character is not yet finished, return
   //transmission is finished when tx_shift_reg == 0
   if(td){return;}
   //fill the TX shift register witch the character to be sent and the start & stop bits
   td = (character<<1) | /* &= ~(1<<0) | start bit is already 0 */  (1<<9); //stop bit
   tx_shift_reg = td;
   //start timer0 with a prescaler of 8
   TCCR0B = (1<<CS01);
}

//timer0 compare A match interrupt
ISR(TIM0_COMPA_vect )
{
   uint16_t td = tx_shift_reg;
   //output LSB of the TX shift register at the TX pin
   if( td & 0x01 ) {
      TX_PORT |= (1<<TX_PIN);
   } else {
      TX_PORT &=~ (1<<TX_PIN);
   }
   //shift the TX shift register one bit to the right
   td >>= 1;
   tx_shift_reg = td;

   //if the stop bit has been sent, the shift register will be 0
   //and the transmission is completed, so we can stop & reset timer0
   if(!td) {
      TCCR0B = 0;
      TCNT0 = 0;
   }
}
~~~
(Code compiled, but not actually tested.)
Before:
00000056 00000042 T UART_tx
000000d0 00000052 T __vector_9
After:
00000056 00000020 T UART_tx
00000076 0000004c T __vector_9

**Comment by MarcelMG** [comment]
Thank you for this advice, I'm always glad to learn something new. But I think I didn't really understand why it is faster like this. Is it because
```tx_shift_reg = (character<<1) | (1<<9);```
is only one write-operation to 'tx_shift_reg' vs.
```
tx_shift_reg = (character<<1);
tx_shift_reg &= ~(1<<0); //start bit
tx_shift_reg |= (1<<9); //stop bit
```
or does it have something to do with the local copy of the variable? I thought that the compiler would combine the three lines above into one already.
Since I'm by no means an expert, I appreciate the opportunity to learn something new.

**Comment by WestfW** [comment]
> Is it because ... is only one write-operation

Essentially.  Since tx_shift_reg is declared as volatile, you're instructing the compiler to "really access this location whenever it is used."  That necessary when you're accessing the variable from different "threads" (main thread vs interrupt thread, in this case) and don't want the compiler to optimize away an access to a variable that has changed.

But within the ISR, other execution is locked out anyway, so you don't need all those accesses.
For the sequence:
```
if(tx_shift_reg){return;}  // read the volatile register and check.
tx_shift_reg = (character<<1);  // write to volatile register.
tx_shift_reg &= ~(1<<0);        // read the volatile register, do the and, write the reg again.
tx_shift_reg |= (1<<9);         // read the volatile register again, do the OR, and write again.
```
So that's six accesses (12 memory accesses, since its an int), probably using a relatively inefficient two-word instruction (LDS/STS to absolute address.)

> I thought that the compiler would combine the three lines above into one already.
It would (probably), except that the "volatile" label on the variable tells it that it MUST NOT do that.
Consider a PORT register sequence to toggle a bit:
```
   PORTB |= 1;
   PORTB &= ~1;
```
If PORTB weren't volatile, the compiler could "combine" those and only execute the second part.
("Clear the bit - fine.  I don't need to set the bit before I clear it!")

by using the local variable (that is NOT volatile), the compiler will read the volatile location once, combine the remaining instructions as they operate on the local, and then write only once...

**Comment by MarcelMG** [comment]
Thank you very much for the explanation, I understand now. I will update the code using your suggested optimization
