### ISSUE TITLE
Attiny13 Fuses

### ISSUE THREAD

**Issue by dimecho** [MarcelMG/AVR8_BitBang_UART_TX#3]
What fuses are you using? I assume you do not divide clock by 8 right?

This is my fuse but cannot receive properly - text all ASCII scrambled.
```
-Uhfuse:w:0xFF:m -Ulfuse:w:0x7A:m
```

**Comment by MarcelMG** [comment]
As you can read in the README, I used the internal 8MHz clock with no prescaler, so F_CPU=8000000. I clock the timer0 with 1MHz by setting the timer prescaler to 8 ( see line 35:    TCCR0B = (1<<CS01); ). So if you want to clock your MCU with 1MHz, one possibility is to start the timer0 without prescaler, so it will still be 1MHz. You can do this by replacing the line mentioned by TCCR0B = (1<<CS01); . Alternatively you can modify the value of OCR0A. Or simply change your fuses to not diveide the CPU clock by 8. So many options :)
